### PR TITLE
Improve constraints of composer requirements

### PR DESCRIPTION
**Pull request by christophlehmann**
See also https://getcomposer.org/doc/articles/versions.md#caret-version-range-

### CODE REVIEW

**Comment by christophlehmann** [comment]
I like to install the package in shopware 5.4.3 and it is not possible

**Comment by shyim** [comment]
Thank you ❤️

**Comment by christophlehmann** [comment]
According to SemVer it's better to not pin the patch version.

**Comment by christophlehmann** [comment]
On packagist.org you can configure a webhook for automatic updating packagists information about the repository :-) Currently the old constraints are shown

**Comment by shyim** [comment]
updated

**Pull request merged**
